### ISSUE TITLE
Please collaborate for benefit of us all

### ISSUE THREAD

**Issue by Vampire** [thiakil/asm-bytecode-intellij#2]
You and elitegit/asm-intellij-plugin are both forks of melix/asm-bytecode-intellij even if he is not technically a fork on GitHub.
Could you two maybe join forces to prevent duplicating work for our all benefit? :-)
You e. g. both fixed the settings dialog.

And if you will not join forces, then please at least make your plugins compatible.
If both are installed, you get a bunch of errors in the idea.log and only one will work, as the actions and tool windows and so on are named the same.

**Comment by thiakil** [comment]
Incompatibilities like that are part and parcel of forks born out of abandonment unfortunately, just don't install both.

I am not against working together

**Comment by Vampire** [comment]
Well, not necessarily. I know such forks more that they slightly (or not so slightly) change naming and so on to be different even from the main project.  The other fork did it partly by changing the JAR name. I was actually quite surprises when installing your fork did automatically uninstall the main project, due to the same file naming. If you do not join forces and not make the plugins compatible, you could also consider using the same file name, so that installing one automatically uninstalls the other. But I'll not sure whether this is actually a bug or a feature, I'd at least expect a message dialog from IJ.

**Comment by thiakil** [comment]
I seem to recall that there is a field that can be added to the xml to say 'incompatible with', will look into it at some stage.

Originally I intended to PR the fixes upstream, though I think it seemed abandoned enough to just re-release as a fork. That or I just got lazy / forgot

**Comment by Vampire** [comment]
Sure, nothing is wrong with releasing a fork if the original project is abandoned.
But I just thought it would make more sense to collaborate on one successor fork instead of creating two that don't work together properly. :-)

**Comment by thiakil** [comment]
Oh for sure. Things may have simply been a case of bad timing; from the git history it seems like I started earlier, but that says nothing about whether this fork was discoverable or not at the point the other author started

**Comment by Vampire** [comment]
Yeah, sure, you alse both released almost at the same time.
Don't get me wrong, I'm not blaming anyone.
I love you too for reviving the project.
I just thought you might not know of each other and I bring you together. :-)

**Comment by thiakil** [comment]
I indeed did not know of the other, so I am thankful :)
